### ISSUE TITLE
Bug with back stack screen(expo router) on IOS

### ISSUE THREAD

**Issue by Sep29th** [Skipperlla/rn-swiper-list#35]
https://github.com/user-attachments/assets/4a103767-806e-4989-9a08-e52ff393abf4

**Comment by Skipperlla** [comment]
I guess it is due to the values I give when scrolling left and right, I will look into it.

**Comment by bastiandev** [comment]
I encountered the same issue after migrating my app from JS-based navigation (`@react-navigation/stack`) to native navigation (`@react-navigation/native-stack`). It only occurs on iOS for me and not on Android.

**I looked into it and was able to fix it by putting `overflow: hidden` on the view that wraps my entire page.**

---

And I don't think this is something the library itself should fix:

To apply the same style directly in the library, it would have to wrap all the SwiperCards in a new view in the Swiper component and then hide the overflow on that. However, the cards would then no longer be able to be rendered outside of this container at all when swiping, not even on the same page. For the example app in this repo, this would mean that they could no longer be dragged behind the ActionButtons. In addition, this new view would have to be configurable/stylable by the consuming developers for full flexibility and the library would have to provide props for this.

At most, the animation could be adjusted so that the cards become invisible after they have finished swiping. Still, this would not completely prevent bleeding to another page and would also be more complex to implement.

**Comment by Skipperlla** [comment]
this weekend I will look at this and all other issues and pr's and close them, I apologize to all of you one by one for keeping you waiting so long @bastiandev

**Comment by Skipperlla** [comment]
The best solution for this is to make the x or y value you give x2, because I guess it is only getting `screenWidth` right now, so when you go back to the other screen, you see those cards there, but if you make it `screenWidth * 2`, your problem will be solved.
